import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <nav className="flex items-center justify-between flex-wrap bg-gray-800 p-6">
                    <div className="flex items-center flex-shrink-0 text-white mr-6">
                        <span className="font-semibold text-xl tracking-tight">
                            Standy
                        </span>
                    </div>
                    <div className="block lg:hidden"></div>
                </nav>

                {children}
            </body>
        </html>
    );
}
